// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQSHE_bSZt9x06kZx6COPr-gGpGy6zvPo',
    appId: '1:1041280322187:web:a624db4f11e7080b99628e',
    messagingSenderId: '1041280322187',
    projectId: 'fruit-hub-ac548',
    authDomain: 'fruit-hub-ac548.firebaseapp.com',
    storageBucket: 'fruit-hub-ac548.firebasestorage.app',
    measurementId: 'G-K6R9HFTFPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCryQXlh_o85ERLzVi75UFPfxHh5M3gjTs',
    appId: '1:1041280322187:android:c7d877759e011b8099628e',
    messagingSenderId: '1041280322187',
    projectId: 'fruit-hub-ac548',
    storageBucket: 'fruit-hub-ac548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLgRP2i-hU9HWNDnQhv04vdegJxtkR6zI',
    appId: '1:1041280322187:ios:cf5e9066625796c299628e',
    messagingSenderId: '1041280322187',
    projectId: 'fruit-hub-ac548',
    storageBucket: 'fruit-hub-ac548.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLgRP2i-hU9HWNDnQhv04vdegJxtkR6zI',
    appId: '1:1041280322187:ios:cf5e9066625796c299628e',
    messagingSenderId: '1041280322187',
    projectId: 'fruit-hub-ac548',
    storageBucket: 'fruit-hub-ac548.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQSHE_bSZt9x06kZx6COPr-gGpGy6zvPo',
    appId: '1:1041280322187:web:12ee1a89a460418199628e',
    messagingSenderId: '1041280322187',
    projectId: 'fruit-hub-ac548',
    authDomain: 'fruit-hub-ac548.firebaseapp.com',
    storageBucket: 'fruit-hub-ac548.firebasestorage.app',
    measurementId: 'G-E1YQ44HKB7',
  );
}
